### ISSUE TITLE
canonical transcripts, gene model, genomic coordinates

### ISSUE THREAD

**Issue by cchng** [UCSC-Treehouse/pipelines#1]
Hi,

I'm processing some expression data from your project.
I have a list of gene symbols and my goal is to get their corresponding genomic coordinates.
How are gencode transcripts converted to gene symbols in your pipeline? For example, is there a list of canonical transcripts? Are values collapsed/averaged?
Any input on your post-processing/consolidate output step seen [here](https://xenabrowser.net/datapages/?host=https://toil.xenahubs.net) would be appreciated!

Thanks,
Carolyn

**Comment by rcurrie** [comment]
Hi Carolyn,

The underlying pipeline is linked from the README:

https://github.com/BD2KGenomics/toil-rnaseq

Look through the primary python pipeline file for details on what's being called and all the processing details:

https://github.com/BD2KGenomics/toil-rnaseq/blob/master/src/toil_rnaseq/rnaseq_cgl_pipeline.py

Rob

**Comment by cchng** [comment]
Thanks Rob!
