### ISSUE TITLE
fix source of input bam in  the methods.json file for variant calling

### ISSUE THREAD

**Issue by e-t-k** [UCSC-Treehouse/pipelines#19]
Thanks @hbeale for spotting this.

The methods.json for variants still claims the bam is coming from `ucsc_cgl-rnaseq-cgl-pipeline` when instead it is actually coming from `ucsctreehouse-bam-umend-qc` - update the code [here](https://github.com/UCSC-Treehouse/pipelines/blob/master/fabfile.py#L494) with correct hash.

We should probably also retroactively correct the outputs from this version as the line; can detect by the line's change from `sorted.bam` to `sortedByCoord.md.bam`:

https://github.com/UCSC-Treehouse/pipelines/commit/dca77ed4987640ef949cde0aeaf50bc49a3d0364#diff-65218180447789ae9b6a89838c1966c9L485

**Comment by rcurrie** [comment]
master's Makefile still has the incorrect variant on the expression vs. qc bam. Looks like there have also been some other changes to treeshop so I'm hesitant to do the fixes. @aglyle or @e-t-k do you want to update and remove the other branches or I can if there are no other changes. Not exactly sure what katrina et. al. are running - hopefully not master...

**Comment by rcurrie** [comment]
@aglyle @e-t-k Ignore - the master Makefile is pulling from qc for variants...brain toast from dna nexus hacking...time to make dinner...
